CREATE TABLE TeamMatchStats (
  id int NOT NULL AUTO_INCREMENT,
  match_id int,
  team_id int,
  opponent_id int,
  is_winner boolean,
  points int,
  tries int,
  conversions int,
  penalty_goals int,
  conversion_percentage varchar(10),
  field_goals int,
  runs int,
  run_metres int,
  metres_per_run varchar(10),
  kick_return_metres int,
  post_contact_metres int,
  line_breaks int,
  line_engaged_runs int,
  tackle_breaks int,
  hit_ups int,
  dummy_half_runs int,
  offloads int,
  passes int,
  tackles int,
  missed_tackles int,
  ineffective_tackles int,
  tackle_percentage varchar(10),
  kicks int,
  kicking_metres int,
  metres_per_kick varchar(10),
  errors int,
  handling_errors int,
  penalties int,
  sin_bins int,
  send_offs int,
  fullback int,
  wing_1 int,
  wing_2 int,
  centre_1 int,
  centre_2 int,
  five_eighth int,
  halfback int,
  prop_1 int,
  prop_2 int,
  hooker int,
  sr_1 int,
  sr_2 int,
  lock int,
  int_1 int,
  int_2 int,
  int_3 int,
  int_4 int,
  PRIMARY KEY (id),
  FOREIGN KEY (match_id) REFERENCES Matches(id),
  FOREIGN KEY (team_id) REFERENCES Teams(id),
  FOREIGN KEY (opponent_id) REFERENCES Teams(id),
  FOREIGN KEY (fullback) REFERENCES Players(id),
  FOREIGN KEY (wing_1) REFERENCES Players(id),
  FOREIGN KEY (wing_2) REFERENCES Players(id),
  FOREIGN KEY (centre_1) REFERENCES Players(id),
  FOREIGN KEY (centre_2) REFERENCES Players(id),
  FOREIGN KEY (five_eighth) REFERENCES Players(id),
  FOREIGN KEY (halfback) REFERENCES Players(id),
  FOREIGN KEY (prop_1) REFERENCES Players(id),
  FOREIGN KEY (prop_2) REFERENCES Players(id),
  FOREIGN KEY (hooker) REFERENCES Players(id),
  FOREIGN KEY (sr_1) REFERENCES Players(id),
  FOREIGN KEY (sr_2) REFERENCES Players(id),
  FOREIGN KEY (lock) REFERENCES Players(id),
  FOREIGN KEY (int_1) REFERENCES Players(id),
  FOREIGN KEY (int_2) REFERENCES Players(id),
  FOREIGN KEY (int_3) REFERENCES Players(id),
  FOREIGN KEY (int_4) REFERENCES Players(id)
);
