CREATE TABLE PlayerMatchStats (
  id int NOT NULL AUTO_INCREMENT,
  match_id int,
  player_id int,
  team_id int,
  position_id int,
  minutes_played int,
  points int,
  tries int,
  conversions int,
  conversion_attempts int,
  penalty_goals int,
  conversion_percentage varchar(10),
  field_goals int,
  total_runs int,
  total_run_metres int,
  kick_return_metres int,
  post_contact_metres int,
  line_breaks int,
  line_break_assists int,
  try_assists int,
  line_engaged_runs int,
  tackle_breaks int,
  hit_ups int,
  play_the_ball int,
  average_play_ball_seconds int,
  dummy_half_runs int,
  dummy_half_run_metres int,
  steals int,
  offloads int,
  dummy_passes int,
  passes int,
  receipts int,
  pass_to_run_ratio varchar(10),
  tackle_percentage varchar(10),
  tackles_made int,
  tackles_missed int,
  intercepts int,
  kicks_defused int,
  kicks int,
  kicking_metres int,
  forced_drop_outs int,
  bomb_kicks int,
  grubbers int,
  fourty_twenty int,
  cross_field_kicks int,
  kicked_dead int,
  errors int,
  handling_errors int,
  one_on_ones_lost int,
  penalties int,
  on_report int,
  sin_bins int,
  send_offs int,
  stint_one varchar(10),
  stint_two varchar(10),

  PRIMARY KEY (id),
  FOREIGN KEY (match_id) REFERENCES Matches(id),
  FOREIGN KEY (player_id) REFERENCES Players(id),
  FOREIGN KEY (team_id) REFERENCES Teams(id),
  FOREIGN KEY (position_id) REFERENCES Positions(id)
);
